import localFont from "next/font/local";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import { Poppins } from 'next/font/google';

const poppins = Poppins({
  weight: '400',
  subsets: ['latin'],
});

export const metadata = {
  title: "GraphList",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <link
        rel="icon"
        href="/icon.png"
        type="image/png"
        sizes="<generated>"
      />
      <body
        className={poppins.className}
      >
        {children}
      </body>
    </html>
  );
}
